import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css"
const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });


export const metadata: Metadata = {
  title: "Audiophile",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={manrope.variable}>
      <body className="bg-white"
      >

        {children}

      </body>
    </html>
  );
}
